# pull official base image
FROM node:21.0.0-alpine

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

RUN npm install -g serve

# add app
COPY . ./

EXPOSE 3000

RUN npm run build

# start app
CMD ["serve", "-s", "build"]
