# pull official base image
FROM node:18.18.2-alpine

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# add app
COPY . ./

EXPOSE 3000

# start app
CMD ["npm", "start"]